[tool.poetry]
name = "cave-explorer"
version = "0.1.0"
description = ""
authors = ["Ben Pedigo <ben.pedigo@alleninstitute.org>"]

[tool.poetry.dependencies]
python = "3.11.*"
scikit-learn = "^1.3.1"
caveclient = "^5.11.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
flake8 = "^3.9.2"
rope = "^0.20.1"
jupyter = "^1.0.0"
jupyter-book = "^0.12.1"
jupytext = "^1.13.8"
ghp-import = "^2.0.1"
ipykernel = "^6.6.0"