[tool.poetry]
name = "cave-explorer"
version = "0.1.0"
description = ""
authors = ["Ben Pedigo <ben.pedigo@alleninstitute.org>"]

[tool.poetry.dependencies]
python = "3.11.*"
scikit-learn = "^1.3.1"
caveclient = "^5.11.0"
graspologic = "^3.3.0"
matplotlib-venn = "^0.11.9"
urllib3 = "^1.26.17"
brotlicffi = "^1.1.0.0"
cloud-volume = "^8.27.0"
meshparty = "^1.16.14"
pcg-skel = "^0.3.4"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
flake8 = "^3.9.2"
rope = "^0.20.1"
jupyter = "^1.0.0"
jupytext = "^1.13.8"
ipykernel = "^6.6.0"