project:
  type: website

website:
  title: "Proofreading retrospective"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/bdpedigo/skedits
          - text: Report a Bug
            url: https://github.com/bdpedigo/skedits/issues/new
  open-graph: true
  sidebar:
    style: "docked"
    search: false
    contents:
      - index.qmd
      - introduction.qmd
      - methods.qmd
      - section: Results
        contents:
          - neuronwise.qmd
          - importance.qmd
          - networkwise.qmd
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: whenSidebarOpen
    giscus: 
      repo: bdpedigo/skedits

  repo-url: https://github.com/bdpedigo/skedits
  repo-actions: [edit, issue]

format:
  html:
    theme: minty
    css: styles.css
    toc: true

execute:
  freeze: auto

filters: 
  - lightbox

lightbox: auto
