---
title: Abstract
date: 2023-12-01
author:
  - name: Benjamin D. Pedigo
    id: bdp
    orcid: 0000-0002-9519-1190
    email: ben.pedigo@alleninstitute.org
    corresponding: true
    affiliation:
      - ref: allen
        # - name: Allen Institute for Brain Science
        # - city: Seattle
affiliations: 
  - id: allen
    name: Allen Institute for Brain Science
    city: Seattle
    state: WA
    url: https://alleninstitute.org/
    ror: https://ror.org/03cpe7c52
---


::: {.justify}

Historically, connectomes have been extremely labor-intensive to generate, requiring vast amounts of person-hours to annotate electron microscopy (EM) image volumes. Automated reconstruction from EM images using computer vision has recently developed to the point where it is being deployed widely to reconstruct connectomes at unprecedented scales. However, these automated techniques, while impressive, typically still have many errors that require human proofreading of these datasets, which involves linking together fragments of the same neuron which have been separated or separating false-merges of distinct cells. Here, we study the effect that these proofreading modifications have on the cortical wiring diagram of a region of mouse visual cortex. We compute several connectivity metrics such as the probability of two cell types or two specific neurons connecting, and study how this connectivity changes as we artificially replay a specific subset of edits onto the neurons in the volume. We show that while `X` changes drastically with proofreading, `Z` and `Y` metrics are relatively stable after a key subset of edits are applied. Our analysis reveals quantitative estimates of one aspect of the variability associated with connectome reconstruction, a key part of the interpretation of inferences in connectomics including comparisons between datasets. Our work also lays the foundation for a quantitative assessment of which areas for human or machine proofreading will be the most influential for downstream analysis, guiding future connectomics reconstructions towards answering scientific questions with a practical amount of effort.

:::